# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hmd_designer_gui_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(972, 1042)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedPages = QtGui.QStackedWidget(self.centralwidget)
        self.stackedPages.setObjectName(_fromUtf8("stackedPages"))
        self.pageNewProject = QtGui.QWidget()
        self.pageNewProject.setObjectName(_fromUtf8("pageNewProject"))
        self.formLayout_3 = QtGui.QFormLayout(self.pageNewProject)
        self.formLayout_3.setMargin(13)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.groupOpenProject = QtGui.QGroupBox(self.pageNewProject)
        self.groupOpenProject.setObjectName(_fromUtf8("groupOpenProject"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupOpenProject)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listboxProjects = QtGui.QListWidget(self.groupOpenProject)
        self.listboxProjects.setObjectName(_fromUtf8("listboxProjects"))
        self.gridLayout_4.addWidget(self.listboxProjects, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.buttonOpenProject = QtGui.QPushButton(self.groupOpenProject)
        self.buttonOpenProject.setObjectName(_fromUtf8("buttonOpenProject"))
        self.verticalLayout_2.addWidget(self.buttonOpenProject)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.buttonDeleteProject = QtGui.QPushButton(self.groupOpenProject)
        self.buttonDeleteProject.setObjectName(_fromUtf8("buttonDeleteProject"))
        self.horizontalLayout_5.addWidget(self.buttonDeleteProject)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.groupOpenProject)
        self.groupNewProject = QtGui.QGroupBox(self.pageNewProject)
        self.groupNewProject.setObjectName(_fromUtf8("groupNewProject"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupNewProject)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonNewProjectCreate = QtGui.QPushButton(self.groupNewProject)
        self.buttonNewProjectCreate.setObjectName(_fromUtf8("buttonNewProjectCreate"))
        self.gridLayout_2.addWidget(self.buttonNewProjectCreate, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupNewProject)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.textNewProjectName = QtGui.QLineEdit(self.groupNewProject)
        self.textNewProjectName.setObjectName(_fromUtf8("textNewProjectName"))
        self.gridLayout_2.addWidget(self.textNewProjectName, 0, 1, 1, 1)
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupNewProject)
        self.stackedPages.addWidget(self.pageNewProject)
        self.pageProjectEditor = QtGui.QWidget()
        self.pageProjectEditor.setObjectName(_fromUtf8("pageProjectEditor"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pageProjectEditor)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupProject = QtGui.QGroupBox(self.pageProjectEditor)
        self.groupProject.setObjectName(_fromUtf8("groupProject"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupProject)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupCadFiles = QtGui.QGroupBox(self.groupProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupCadFiles.sizePolicy().hasHeightForWidth())
        self.groupCadFiles.setSizePolicy(sizePolicy)
        self.groupCadFiles.setObjectName(_fromUtf8("groupCadFiles"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupCadFiles)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.comboModelFiles = QtGui.QComboBox(self.groupCadFiles)
        self.comboModelFiles.setObjectName(_fromUtf8("comboModelFiles"))
        self.gridLayout_8.addWidget(self.comboModelFiles, 3, 1, 1, 1)
        self.lblInputFiles = QtGui.QLabel(self.groupCadFiles)
        self.lblInputFiles.setObjectName(_fromUtf8("lblInputFiles"))
        self.gridLayout_8.addWidget(self.lblInputFiles, 8, 1, 1, 1)
        self.lblObstaclesList = QtGui.QLabel(self.groupCadFiles)
        self.lblObstaclesList.setObjectName(_fromUtf8("lblObstaclesList"))
        self.gridLayout_8.addWidget(self.lblObstaclesList, 6, 1, 1, 1)
        self.buttonBrowseForInputFile = QtGui.QPushButton(self.groupCadFiles)
        self.buttonBrowseForInputFile.setObjectName(_fromUtf8("buttonBrowseForInputFile"))
        self.gridLayout_8.addWidget(self.buttonBrowseForInputFile, 9, 1, 1, 1)
        self.lblSensorsInputFile = QtGui.QLabel(self.groupCadFiles)
        self.lblSensorsInputFile.setObjectName(_fromUtf8("lblSensorsInputFile"))
        self.gridLayout_8.addWidget(self.lblSensorsInputFile, 4, 1, 1, 1)
        self.lblModelInputJson = QtGui.QLabel(self.groupCadFiles)
        self.lblModelInputJson.setObjectName(_fromUtf8("lblModelInputJson"))
        self.gridLayout_8.addWidget(self.lblModelInputJson, 2, 1, 1, 1)
        self.comboSensorsFile = QtGui.QComboBox(self.groupCadFiles)
        self.comboSensorsFile.setObjectName(_fromUtf8("comboSensorsFile"))
        self.gridLayout_8.addWidget(self.comboSensorsFile, 5, 1, 1, 1)
        self.listboxObstacles = QtGui.QListWidget(self.groupCadFiles)
        self.listboxObstacles.setObjectName(_fromUtf8("listboxObstacles"))
        self.gridLayout_8.addWidget(self.listboxObstacles, 7, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 7, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_9)
        self.gridLayout_7.addWidget(self.groupCadFiles, 0, 0, 1, 1)
        self.groupSimulate = QtGui.QGroupBox(self.groupProject)
        self.groupSimulate.setObjectName(_fromUtf8("groupSimulate"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupSimulate)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblNumSensors = QtGui.QLabel(self.groupSimulate)
        self.lblNumSensors.setObjectName(_fromUtf8("lblNumSensors"))
        self.gridLayout_6.addWidget(self.lblNumSensors, 0, 0, 1, 1)
        self.buttonSimulate = QtGui.QPushButton(self.groupSimulate)
        self.buttonSimulate.setObjectName(_fromUtf8("buttonSimulate"))
        self.gridLayout_6.addWidget(self.buttonSimulate, 5, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupSimulate)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinPermutations = QtGui.QSpinBox(self.groupSimulate)
        self.spinPermutations.setMinimum(1)
        self.spinPermutations.setMaximum(12)
        self.spinPermutations.setProperty("value", 1)
        self.spinPermutations.setObjectName(_fromUtf8("spinPermutations"))
        self.gridLayout_6.addWidget(self.spinPermutations, 3, 1, 1, 2)
        self.spinNumSensors = QtGui.QSpinBox(self.groupSimulate)
        self.spinNumSensors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinNumSensors.setMinimum(5)
        self.spinNumSensors.setMaximum(32)
        self.spinNumSensors.setProperty("value", 32)
        self.spinNumSensors.setObjectName(_fromUtf8("spinNumSensors"))
        self.gridLayout_6.addWidget(self.spinNumSensors, 0, 1, 1, 2)
        self.spinBoxMaxNormalShift = QtGui.QDoubleSpinBox(self.groupSimulate)
        self.spinBoxMaxNormalShift.setDecimals(0)
        self.spinBoxMaxNormalShift.setMaximum(90.0)
        self.spinBoxMaxNormalShift.setSingleStep(5.0)
        self.spinBoxMaxNormalShift.setObjectName(_fromUtf8("spinBoxMaxNormalShift"))
        self.gridLayout_6.addWidget(self.spinBoxMaxNormalShift, 2, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupSimulate)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        self.buttonEchoCommand = QtGui.QPushButton(self.groupSimulate)
        self.buttonEchoCommand.setObjectName(_fromUtf8("buttonEchoCommand"))
        self.gridLayout_6.addWidget(self.buttonEchoCommand, 5, 0, 1, 1)
        self.comboBoxSimulationQuality = QtGui.QComboBox(self.groupSimulate)
        self.comboBoxSimulationQuality.setEditable(False)
        self.comboBoxSimulationQuality.setObjectName(_fromUtf8("comboBoxSimulationQuality"))
        self.comboBoxSimulationQuality.addItem(_fromUtf8(""))
        self.comboBoxSimulationQuality.addItem(_fromUtf8(""))
        self.comboBoxSimulationQuality.addItem(_fromUtf8(""))
        self.comboBoxSimulationQuality.addItem(_fromUtf8(""))
        self.comboBoxSimulationQuality.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBoxSimulationQuality, 1, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupSimulate)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupSimulate, 2, 0, 1, 1)
        self.groupVisualize = QtGui.QGroupBox(self.groupProject)
        self.groupVisualize.setObjectName(_fromUtf8("groupVisualize"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupVisualize)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.buttonVisualizeModel = QtGui.QPushButton(self.groupVisualize)
        self.buttonVisualizeModel.setObjectName(_fromUtf8("buttonVisualizeModel"))
        self.verticalLayout_5.addWidget(self.buttonVisualizeModel)
        self.gridLayout_7.addWidget(self.groupVisualize, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_7)
        self.groupResults = QtGui.QGroupBox(self.groupProject)
        self.groupResults.setObjectName(_fromUtf8("groupResults"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupResults)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkView3d = QtGui.QCheckBox(self.groupResults)
        self.checkView3d.setObjectName(_fromUtf8("checkView3d"))
        self.gridLayout_3.addWidget(self.checkView3d, 0, 1, 1, 1)
        self.checkView2d = QtGui.QCheckBox(self.groupResults)
        self.checkView2d.setObjectName(_fromUtf8("checkView2d"))
        self.gridLayout_3.addWidget(self.checkView2d, 0, 0, 1, 1)
        self.checkViewOutputScad = QtGui.QCheckBox(self.groupResults)
        self.checkViewOutputScad.setObjectName(_fromUtf8("checkViewOutputScad"))
        self.gridLayout_3.addWidget(self.checkViewOutputScad, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.groupResults)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.tabSims = QtGui.QTabWidget(self.groupResults)
        self.tabSims.setObjectName(_fromUtf8("tabSims"))
        self.tabSimulations = QtGui.QWidget()
        self.tabSimulations.setObjectName(_fromUtf8("tabSimulations"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSimulations)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.vertProgressLayout = QtGui.QVBoxLayout()
        self.vertProgressLayout.setObjectName(_fromUtf8("vertProgressLayout"))
        self.verticalLayout_3.addLayout(self.vertProgressLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 392, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabSims.addTab(self.tabSimulations, _fromUtf8(""))
        self.tabArchives = QtGui.QWidget()
        self.tabArchives.setObjectName(_fromUtf8("tabArchives"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabArchives)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.vertArchiveLayout = QtGui.QVBoxLayout()
        self.vertArchiveLayout.setObjectName(_fromUtf8("vertArchiveLayout"))
        self.verticalLayout_4.addLayout(self.vertArchiveLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 392, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabSims.addTab(self.tabArchives, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabSims)
        self.horizontalLayout_4.addWidget(self.groupResults)
        self.horizontalLayout.addWidget(self.groupProject)
        self.stackedPages.addWidget(self.pageProjectEditor)
        self.pagePreferences = QtGui.QWidget()
        self.pagePreferences.setObjectName(_fromUtf8("pagePreferences"))
        self.formLayout = QtGui.QFormLayout(self.pagePreferences)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupPreferences = QtGui.QGroupBox(self.pagePreferences)
        self.groupPreferences.setObjectName(_fromUtf8("groupPreferences"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupPreferences)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupPreferences)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.textOpenScad = QtGui.QLineEdit(self.groupPreferences)
        self.textOpenScad.setObjectName(_fromUtf8("textOpenScad"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.textOpenScad)
        self.label_6 = QtGui.QLabel(self.groupPreferences)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_3 = QtGui.QLabel(self.groupPreferences)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.checkPersistence = QtGui.QCheckBox(self.groupPreferences)
        self.checkPersistence.setChecked(True)
        self.checkPersistence.setObjectName(_fromUtf8("checkPersistence"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkPersistence)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonPrefSave = QtGui.QPushButton(self.groupPreferences)
        self.buttonPrefSave.setObjectName(_fromUtf8("buttonPrefSave"))
        self.horizontalLayout_2.addWidget(self.buttonPrefSave)
        self.buttonPrefCancel = QtGui.QPushButton(self.groupPreferences)
        self.buttonPrefCancel.setObjectName(_fromUtf8("buttonPrefCancel"))
        self.horizontalLayout_2.addWidget(self.buttonPrefCancel)
        self.formLayout_2.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.checkOverridePath = QtGui.QCheckBox(self.groupPreferences)
        self.checkOverridePath.setChecked(False)
        self.checkOverridePath.setObjectName(_fromUtf8("checkOverridePath"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkOverridePath)
        self.textProjectPath = QtGui.QLineEdit(self.groupPreferences)
        self.textProjectPath.setObjectName(_fromUtf8("textProjectPath"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.textProjectPath)
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupPreferences)
        self.stackedPages.addWidget(self.pagePreferences)
        self.gridLayout.addWidget(self.stackedPages, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewProject = QtGui.QAction(MainWindow)
        self.actionNewProject.setObjectName(_fromUtf8("actionNewProject"))
        self.actionOpenProject = QtGui.QAction(MainWindow)
        self.actionOpenProject.setObjectName(_fromUtf8("actionOpenProject"))
        self.actionCloseProject = QtGui.QAction(MainWindow)
        self.actionCloseProject.setObjectName(_fromUtf8("actionCloseProject"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionSaveProject = QtGui.QAction(MainWindow)
        self.actionSaveProject.setObjectName(_fromUtf8("actionSaveProject"))
        self.menuFile.addAction(self.actionNewProject)
        self.menuFile.addAction(self.actionSaveProject)
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedPages.setCurrentIndex(2)
        self.comboBoxSimulationQuality.setCurrentIndex(1)
        self.tabSims.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HMD Designer GUI", None))
        self.groupOpenProject.setTitle(_translate("MainWindow", "Open Project", None))
        self.buttonOpenProject.setText(_translate("MainWindow", "Open", None))
        self.buttonDeleteProject.setText(_translate("MainWindow", "Delete", None))
        self.groupNewProject.setTitle(_translate("MainWindow", "New Project", None))
        self.buttonNewProjectCreate.setText(_translate("MainWindow", "Create", None))
        self.label.setText(_translate("MainWindow", "Project Name", None))
        self.groupProject.setTitle(_translate("MainWindow", "Project - Default Project", None))
        self.groupCadFiles.setTitle(_translate("MainWindow", "Files", None))
        self.lblInputFiles.setText(_translate("MainWindow", "Input Files (.json, .stl, .scad)", None))
        self.lblObstaclesList.setText(_translate("MainWindow", "Obstacles (.stl or .scad)", None))
        self.buttonBrowseForInputFile.setText(_translate("MainWindow", "Add Input File...", None))
        self.lblSensorsInputFile.setText(_translate("MainWindow", "Sensor Object (.stl or .scad)", None))
        self.lblModelInputJson.setText(_translate("MainWindow", "Model (.json)", None))
        self.groupSimulate.setTitle(_translate("MainWindow", "Simulate", None))
        self.lblNumSensors.setText(_translate("MainWindow", "Total Sensors", None))
        self.buttonSimulate.setText(_translate("MainWindow", "Simulate", None))
        self.label_4.setText(_translate("MainWindow", "Number of Permutations", None))
        self.label_2.setText(_translate("MainWindow", "Max Normal Shift (degrees)", None))
        self.buttonEchoCommand.setText(_translate("MainWindow", "Echo Command", None))
        self.comboBoxSimulationQuality.setItemText(0, _translate("MainWindow", "Max (0.95)", None))
        self.comboBoxSimulationQuality.setItemText(1, _translate("MainWindow", "High (0.90)", None))
        self.comboBoxSimulationQuality.setItemText(2, _translate("MainWindow", "Medium (0.80)", None))
        self.comboBoxSimulationQuality.setItemText(3, _translate("MainWindow", "Low (0.70)", None))
        self.comboBoxSimulationQuality.setItemText(4, _translate("MainWindow", "Test (0.10)", None))
        self.label_7.setText(_translate("MainWindow", "Simulation Quality", None))
        self.groupVisualize.setTitle(_translate("MainWindow", "Visualize", None))
        self.buttonVisualizeModel.setText(_translate("MainWindow", "Visualize Model", None))
        self.groupResults.setTitle(_translate("MainWindow", "Results", None))
        self.checkView3d.setText(_translate("MainWindow", "3D Simulation", None))
        self.checkView2d.setText(_translate("MainWindow", "2D Plots", None))
        self.checkViewOutputScad.setText(_translate("MainWindow", "Output SCAD", None))
        self.tabSims.setTabText(self.tabSims.indexOf(self.tabSimulations), _translate("MainWindow", "Simulations", None))
        self.tabSims.setTabText(self.tabSims.indexOf(self.tabArchives), _translate("MainWindow", "Archives", None))
        self.groupPreferences.setTitle(_translate("MainWindow", "Preferences", None))
        self.label_5.setText(_translate("MainWindow", "OpenSCAD", None))
        self.label_6.setText(_translate("MainWindow", "Projects Path", None))
        self.label_3.setText(_translate("MainWindow", "Persistence", None))
        self.checkPersistence.setText(_translate("MainWindow", "Enable persistent project settings (automatically save changes)", None))
        self.buttonPrefSave.setText(_translate("MainWindow", "Save", None))
        self.buttonPrefCancel.setText(_translate("MainWindow", "Cancel", None))
        self.checkOverridePath.setText(_translate("MainWindow", "Override default projects directory path", None))
        self.textProjectPath.setText(_translate("MainWindow", "C:\\", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionNewProject.setText(_translate("MainWindow", "New/Open", None))
        self.actionOpenProject.setText(_translate("MainWindow", "Open Project", None))
        self.actionCloseProject.setText(_translate("MainWindow", "Close Project", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences...", None))
        self.actionSaveProject.setText(_translate("MainWindow", "Save", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

